obj-$(CONFIG_MACH_LGE) += devices_lge.o

obj-$(CONFIG_MACH_MSM8X26_LGPS14) += board-8226-lgps14.o board-8226-lgps14-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_W7DS_OPEN_CIS) += board-8226-w7ds-open-cis.o board-8226-w7ds-open-cis-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_W7DS_GLOBAL_SCA) += board-8226-w7ds-global-sca.o board-8226-w7ds-global-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_W7DS_GLOBAL_COM) += board-8226-w7ds-global-com.o board-8226-w7ds-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_W7_OPEN_CIS) += board-8226-w7-open-cis.o board-8226-w7-open-cis-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_W7_OPEN_EU) += board-8226-w7-open-eu.o board-8226-w7-open-eu-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_W7_GLOBAL_COM) += board-8226-w7-global-com.o board-8226-w7-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_W7_GLOBAL_SCA) += board-8226-w7-global-sca.o board-8226-w7-global-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_W7_TMO_US) += board-8226-w7-tmo-us.o board-8226-w7-tmo-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_G2MDS_OPEN_CIS) += board-8226-g2mds-open-cis.o board-8226-g2mds-open-cis-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_G2MDS_GLOBAL_COM) += board-8226-g2mds-global-com.o board-8226-g2mds-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_G2MSS_GLOBAL_COM) += board-8226-g2mss-global-com.o board-8226-g2mss-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X5_VZW) += board-8926-x5-vzw.o board-8926-x5-vzw-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X3C_TRF_US) += board-8926-x3c-trf-us.o board-8926-x3c-trf-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X3N_OPEN_EU) += board-8926-x3n-open-eu.o board-8926-x3n-open-eu-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X3N_GLOBAL_SCA) += board-8926-x3n-global-sca.o board-8926-x3n-global-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X3N_GLOBAL_COM) += board-8926-x3n-global-com.o board-8926-x3n-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X3_TRF_US) += board-8926-x3-trf-us.o board-8926-x3-trf-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X3_KR) += board-8926-x3-kr.o board-8926-x3-kr-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X5_SPR) += board-8926-x5-spr.o board-8926-x5-spr-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X5_OPEN) += board-8926-x5-open.o board-8926-x5-open-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_G2M_VDF) += board-8926-g2m-vdf.o board-8926-g2m-vdf-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_G2M_KR) += board-8926-g2m-kr.o board-8926-g2m-kr-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_G2M_OPEN) += board-8926-g2m-open.o board-8926-g2m-open-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_G2M_GLOBAL) += board-8926-g2m-global.o board-8926-g2m-global-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_G2MH_SBM) += board-8926-g2mh-sbm-jp.o board-8926-g2mh-sbm-jp-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_B1L_VZW) += board-8926-b1l-vzw.o board-8926-b1l-vzw-gpiomux.o board-8926-b1l-vzw-rfkill.o
obj-$(CONFIG_MACH_MSM8926_B1L_ATT) += board-8926-b1l-att_us.o board-8926-b1l-att_us-gpiomux.o board-8926-b1l-att_us-rfkill.o
obj-$(CONFIG_MACH_MSM8X10_LGPS15) += board-8610-lgps15.o board-8610-lgps15-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3C_VZW) += board-8610-w3c-vzw.o board-8610-w3c-vzw-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3C_TRF_US) += board-8610-w3c-trf-us.o board-8610-w3c-trf-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3_VDF_EU) += board-8610-w3-vdf-eu.o board-8610-w3-vdf-eu-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3_VDF_COM) += board-8610-w3-vdf-com.o board-8610-w3-vdf-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3_GLOBAL_COM) += board-8610-w3-global-com.o board-8610-w3-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3_GLOBAL_SCA) += board-8610-w3-global-sca.o board-8610-w3-global-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3DS_OPEN_BR) += board-8610-w3ds-open-br.o board-8610-w3ds-open-br-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3DS_TIM_BR) += board-8610-w3ds-tim-br.o board-8610-w3ds-tim-br-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3DS_OPEN_SCA) += board-8610-w3ds-open-sca.o board-8610-w3ds-open-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3DS_GLOBAL_COM) += board-8610-w3ds-global-com.o board-8610-w3ds-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3TS_OPEN_SCA) += board-8610-w3ts-open-sca.o board-8610-w3ts-open-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5_OPEN_EU) += board-8610-w5-open-eu.o board-8610-w5-open-eu-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5N_VDF_EU) += board-8610-w5n-vdf-eu.o board-8610-w5n-vdf-eu-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5N_GLOBAL_COM) += board-8610-w5n-global-com.o board-8610-w5n-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5_GLOBAL_COM) += board-8610-w5-global-com.o board-8610-w5-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5DS_GLOBAL_COM) += board-8610-w5ds-global-com.o board-8610-w5ds-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W55DS_GLOBAL_COM) += board-8610-w55ds-global-com.o board-8610-w55ds-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5TS_OPEN_SCA) += board-8610-w5ts-open-sca.o board-8610-w5ts-open-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5TS_GLOBAL_COM) += board-8610-w5ts-global-com.o board-8610-w5ts-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5_MPCS_US) += board-8610-w5-mpcs-us.o board-8610-w5-mpcs-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5_AIO_US) += board-8610-w5-aio-us.o board-8610-w5-aio-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3C_TRF_US) += board-8610-w3c-trf-us.o board-8610-w3c-trf-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5C_VZW) += board-8610-w5c-vzw.o board-8610-w5c-vzw-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5C_ACG_US) += board-8610-w5c-acg-us.o board-8610-w5c-acg-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5C_TRF_US) += board-8610-w5c-trf-us.o board-8610-w5c-trf-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5C_SPR_US) += board-8610-w5c-spr-us.o board-8610-w5c-spr-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W6_GLOBAL_COM) += board-8610-w6-global-com.o board-8610-w6-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W6_TCL_MX) += board-8610-w6-tcl-mx.o board-8610-w6-tcl-mx-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W6DS_GLOBAL_COM) += board-8610-w6ds-global-com.o board-8610-w6ds-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W6DS_GLOBAL_SCA) += board-8610-w6ds-global-sca.o board-8610-w6ds-global-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W6DS_TIM_BR) += board-8610-w6ds-tim-br.o board-8610-w6ds-tim-br-gpiomux.o

obj-$(CONFIG_LGE_BOOTLOADER_LOG) += lge_bootloader_log.o
obj-$(CONFIG_LGE_HANDLE_PANIC) += lge_handle_panic.o
obj-$(CONFIG_LGE_BOOTLOADER_TIME_CHECKER) += lge_bootloader_time_checker.o
ifdef CONFIG_MACH_MSM8926_X5_SPR
obj-$(CONFIG_LGE_PM_CHARGING_TEMP_SCENARIO) += lge_charging_scenario_sprint.o
else
obj-$(CONFIG_LGE_PM_CHARGING_TEMP_SCENARIO) += lge_charging_scenario.o
endif
obj-$(CONFIG_MACH_LGE) += lge_kcal_ctrl.o
#[WiFi]_S[sangheon.shim@lge.com] BRCM WLAN
obj-$(CONFIG_WIFI_CONTROL_FUNC) += wifi_bcm_lge.o
obj-$(CONFIG_LGE_QFPROM_INTERFACE) += lge_qfprom_access.o
obj-$(CONFIG_LGE_ENABLE_MMC_STRENGTH_CONTROL) += lge_mmc_strength_control.o

ifneq ($(CONFIG_MACH_MSM8926_B1L_VZW),)
EXTRA_CFLAGS += -DCONFIG_MACH_MSM8926_B1L_VZW
endif
#[Power] Battery Data 
ifdef CONFIG_LGE_PM_BATTERY_PROFILE_DATA
	ifdef CONFIG_LGE_PM_BATTERY_ID_CHECKER
#This is for default setting / remove later
		obj-$(CONFIG_MACH_LGE) += bms-batterydata-LGE_BL_54SH_2540mAh_LG_Chem_Final.o 
		obj-$(CONFIG_LGE_PM_BATTERY_CAPACITY_1540mAh) += bms-batterydata-LGC_BL44JR_1540.o
		obj-$(CONFIG_LGE_PM_BATTERY_CAPACITY_1700mAh) += bms-batterydata-LGC_BL44JH_1700.o bms-batterydata-LGC_BL44JH_1700_Dallas.o bms-batterydata-Tocad_BL44JH_1700_Intersil.o
		obj-$(CONFIG_LGE_PM_BATTERY_CAPACITY_2100mAh) += bms-batterydata-LGE_LGC_2040mAh_Final.o bms-batterydata-LGE_Tocad_2040mAh_Final.o
		obj-$(CONFIG_LGE_PM_BATTERY_CAPACITY_2440mAh) += bms-batterydata-LGE_BL_59UH_2440mAh_LG_Chem_Final.o bms-batterydata-LGE_BL_59UH_2440mAh_TOCAD_Final.o
		obj-$(CONFIG_LGE_PM_BATTERY_CAPACITY_2540mAh) += bms-batterydata-LGE_BL_54SH_2540mAh_LG_Chem_Final.o bms-batterydata-LGE_BL_54SH_2540mAh_Sanyo_Final.o
		obj-$(CONFIG_LGE_PM_BATTERY_CAPACITY_3000mAh) += bms-batterydata-LGE_BL_64SH_3000mAh_LG_Chem_Final.o bms-batterydata-LGE_BL_64SH_3000mAh_Technohill_Final.o
	else
		obj-$(CONFIG_MACH_LGE) += bms-batterydata-LGE_BL_54SH_2540mAh_LG_Chem_Final.o
	endif
endif

CFLAGS_devices_lge.o += -Idrivers/staging/android
