obj-$(CONFIG_MACH_LGE) += devices_lge.o

obj-$(CONFIG_MACH_MSM8X26_LGPS14) += board-8226-lgps14.o board-8226-lgps14-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_W7DS_GLOBAL_COM) += board-8226-w7ds-global-com.o board-8226-w7ds-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_W7_GLOBAL_COM) += board-8226-w7-global-com.o board-8226-w7-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_W7_GLOBAL_SCA) += board-8226-w7-global-sca.o board-8226-w7-global-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_W7DSN_GLOBAL_COM) += board-8226-w7dsn-global-com.o board-8226-w7dsn-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_W7N_GLOBAL_COM) += board-8226-w7n-global-com.o board-8226-w7n-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_W7N_GLOBAL_SCA) += board-8226-w7n-global-sca.o board-8226-w7n-global-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_W7_TMO_US) += board-8226-w7-tmo-us.o board-8226-w7-tmo-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_JAG3GDS_GLOBAL_COM) += board-8226-jag3gds-global-com.o board-8226-jag3gds-global-com-gpiomux.o bluetooth-pm.o
obj-$(CONFIG_MACH_MSM8226_JAG3GSS_GLOBAL_COM) += board-8226-jag3gss-global-com.o board-8226-jag3gss-global-com-gpiomux.o bluetooth-pm.o
obj-$(CONFIG_MACH_MSM8226_G2MDS_OPEN_CIS) += board-8226-g2mds-open-cis.o board-8226-g2mds-open-cis-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_G2MDS_GLOBAL_COM) += board-8226-g2mds-global-com.o board-8226-g2mds-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_G2MSS_GLOBAL_COM) += board-8226-g2mss-global-com.o board-8226-g2mss-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_E9WIFI) += board-8226-e9wifi.o board-8226-e9wifi-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_E9WIFIN) += board-8226-e9wifin.o board-8226-e9wifin-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_E8WIFI) += board-8226-e8wifi.o board-8226-e8wifi-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_E8LTE) += board-8926-e8lte.o board-8926-e8lte-gpiomux.o
obj-$(CONFIG_MACH_MSM8226_E7WIFI) += board-8226-e7wifi.o board-8226-e7wifi-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_AKA_CN) += board-8926-aka-cn.o board-8926-aka-cn-gpiomux.o board-8926-aka-cn-rfkill.o
obj-$(CONFIG_MACH_MSM8926_E7LTE_ATT_US) += board-8926-e7lte-att-us.o board-8926-e7lte-att-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_E7LTE_USC_US) += board-8926-e7lte-usc-us.o board-8926-e7lte-usc-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_E7LTE_VZW_US) += board-8926-e7lte-vzw.o board-8926-e7lte-vzw-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_T8LTE_ATT_US) += board-8926-t8lte-att-us.o board-8926-t8lte-att-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_T8LTE_TMO_US) += board-8926-t8lte-tmo-us.o board-8926-t8lte-tmo-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_T8LTE_USC_US) += board-8926-t8lte-usc-us.o board-8926-t8lte-usc-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_T8LTE_ACG_US) += board-8926-t8lte-acg-us.o board-8926-t8lte-acg-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_E9LTE_VZW_US) += board-8926-e9lte-vzw.o board-8926-e9lte-vzw-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X5_VZW) += board-8926-x5-vzw.o board-8926-x5-vzw-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_E2_SPR_US) += board-8926-e2-spr.o board-8926-e2-spr-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_E2_MPCS_US) += board-8926-e2-mpcs.o board-8926-e2-mpcs-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_E2_BELL_CA) += board-8926-e2-bell.o board-8926-e2-bell-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_E2_RGS_CA) += board-8926-e2-rgs.o board-8926-e2-rgs-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_E2_VTR_CA) += board-8926-e2-vtr.o board-8926-e2-vtr-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_E2_VZW) += board-8926-e2-vzw.o board-8926-e2-vzw-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X5_LRA) += board-8926-x5-lra.o board-8926-x5-lra-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X3C_TRF_US) += board-8926-x3c-trf-us.o board-8926-x3c-trf-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X3N_OPEN_EU) += board-8926-x3n-open-eu.o board-8926-x3n-open-eu-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X3N_GLOBAL_SCA) += board-8926-x3n-global-sca.o board-8926-x3n-global-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X3N_GLOBAL_COM) += board-8926-x3n-global-com.o board-8926-x3n-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_F70N_GLOBAL_COM) += board-8926-f70n-global-com.o board-8926-f70n-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_F70N_GLOBAL_AME) += board-8926-f70n-global-ame.o board-8926-f70n-global-ame-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_F70_GLOBAL_COM) += board-8926-f70-global-com.o board-8926-f70-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X3_TRF_US) += board-8926-x3-trf-us.o board-8926-x3-trf-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X3N_KR) += board-8926-x3n-kr.o board-8926-x3n-kr-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_F70N_KR) += board-8926-f70n-kr.o board-8926-f70n-kr-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X5_SPR) += board-8926-x5-spr.o board-8926-x5-spr-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X5_OPEN) += board-8926-x5-open.o board-8926-x5-open-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_JAGC_SPR) += board-8926-jagc-spr.o board-8926-jagc-spr-gpiomux.o board-8926-jagc-spr-rfkill.o
obj-$(CONFIG_MACH_MSM8926_G2M_VDF) += board-8926-g2m-vdf.o board-8926-g2m-vdf-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_G2M_KR) += board-8926-g2m-kr.o board-8926-g2m-kr-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_G2M_OPEN) += board-8926-g2m-open.o board-8926-g2m-open-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_G2M_GLOBAL) += board-8926-g2m-global.o board-8926-g2m-global-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_G2MH_SBM) += board-8926-g2mh-sbm-jp.o board-8926-g2mh-sbm-jp-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_X10_VZW) += board-8926-x10-vzw.o board-8926-x10-vzw-gpiomux.o board-8926-x10-vzw-rfkill.o
obj-$(CONFIG_MACH_MSM8926_B2L_ATT) += board-8926-b2l-att_us.o board-8926-b2l-att_us-gpiomux.o board-8926-b2l-att_us-rfkill.o
obj-$(CONFIG_MACH_MSM8926_B2LN_KR) += board-8926-b2ln-kr.o board-8926-b2ln-kr-gpiomux.o board-8926-b2ln-kr-rfkill.o
obj-$(CONFIG_MACH_MSM8926_JAGNM_ATT) += board-8926-jagnm-att_us.o board-8926-jagnm-att_us-gpiomux.o board-8926-jagnm-att_us-rfkill.o
obj-$(CONFIG_MACH_MSM8926_JAGNM_BELL) += board-8926-jagnm-bell_ca.o board-8926-jagnm-bell_ca-gpiomux.o board-8926-jagnm-bell_ca-rfkill.o
obj-$(CONFIG_MACH_MSM8926_JAGNM_RGS) += board-8926-jagnm-rgs_ca.o board-8926-jagnm-rgs_ca-gpiomux.o board-8926-jagnm-rgs_ca-rfkill.o
obj-$(CONFIG_MACH_MSM8926_JAGNM_TLS) += board-8926-jagnm-tls_ca.o board-8926-jagnm-tls_ca-gpiomux.o board-8926-jagnm-tls_ca-rfkill.o
obj-$(CONFIG_MACH_MSM8926_JAGNM_VTR) += board-8926-jagnm-vtr_ca.o board-8926-jagnm-vtr_ca-gpiomux.o board-8926-jagnm-vtr_ca-rfkill.o
obj-$(CONFIG_MACH_MSM8926_JAGN_KR) += board-8926-jagn-kr.o board-8926-jagn-kr-gpiomux.o board-8926-jagn-kr-rfkill.o
obj-$(CONFIG_MACH_MSM8926_AKA_KR) += board-8926-aka-kr.o board-8926-aka-kr-gpiomux.o board-8926-aka-kr-rfkill.o
obj-$(CONFIG_MACH_MSM8926_JAGNM_GLOBAL_COM) += board-8926-jagnm-global-com.o board-8926-jagnm-global-com-gpiomux.o bluetooth-pm.o
obj-$(CONFIG_MACH_MSM8926_VFP_KR) += board-8926-vfp-kr.o board-8926-vfp-kr-gpiomux.o board-8926-vfp-kr-rfkill.o
obj-$(CONFIG_MACH_MSM8X10_LGPS15) += board-8610-lgps15.o board-8610-lgps15-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3C_VZW) += board-8610-w3c-vzw.o board-8610-w3c-vzw-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3C_TRF_US) += board-8610-w3c-trf-us.o board-8610-w3c-trf-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3_VDF_EU) += board-8610-w3-vdf-eu.o board-8610-w3-vdf-eu-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3_VDF_COM) += board-8610-w3-vdf-com.o board-8610-w3-vdf-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3_GLOBAL_COM) += board-8610-w3-global-com.o board-8610-w3-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3_GLOBAL_SCA) += board-8610-w3-global-sca.o board-8610-w3-global-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W35_GLOBAL_SCA) += board-8610-w35-global-sca.o board-8610-w35-global-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W35_GLOBAL_COM) += board-8610-w35-global-com.o board-8610-w35-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3DS_OPEN_BR) += board-8610-w3ds-open-br.o board-8610-w3ds-open-br-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3DS_TIM_BR) += board-8610-w3ds-tim-br.o board-8610-w3ds-tim-br-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3DS_OPEN_SCA) += board-8610-w3ds-open-sca.o board-8610-w3ds-open-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3DS_GLOBAL_COM) += board-8610-w3ds-global-com.o board-8610-w3ds-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W35DS_GLOBAL_SCA) += board-8610-w35ds-global-sca.o board-8610-w35ds-global-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3TS_OPEN_SCA) += board-8610-w3ts-open-sca.o board-8610-w3ts-open-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3TS_GLOBAL_SCA) += board-8610-w3ts-global-sca.o board-8610-w3ts-global-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5_OPEN_EU) += board-8610-w5-open-eu.o board-8610-w5-open-eu-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5N_VDF_EU) += board-8610-w5n-vdf-eu.o board-8610-w5n-vdf-eu-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5N_GLOBAL_COM) += board-8610-w5n-global-com.o board-8610-w5n-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5_GLOBAL_COM) += board-8610-w5-global-com.o board-8610-w5-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W55_GLOBAL_COM) += board-8610-w55-global-com.o board-8610-w55-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W55N_GLOBAL_COM) += board-8610-w55n-global-com.o board-8610-w55n-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5DS_GLOBAL_COM) += board-8610-w5ds-global-com.o board-8610-w5ds-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W55DS_GLOBAL_COM) += board-8610-w55ds-global-com.o board-8610-w55ds-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5TS_OPEN_SCA) += board-8610-w5ts-open-sca.o board-8610-w5ts-open-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5TS_GLOBAL_COM) += board-8610-w5ts-global-com.o board-8610-w5ts-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5_MPCS_US) += board-8610-w5-mpcs-us.o board-8610-w5-mpcs-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5_CCA_US) += board-8610-w5-cca-us.o board-8610-w5-cca-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5_AIO_US) += board-8610-w5-aio-us.o board-8610-w5-aio-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5_TRF_US) += board-8610-w5-trf-us.o board-8610-w5-trf-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W3C_TRF_US) += board-8610-w3c-trf-us.o board-8610-w3c-trf-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5C_VZW) += board-8610-w5c-vzw.o board-8610-w5c-vzw-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5C_ACG_US) += board-8610-w5c-acg-us.o board-8610-w5c-acg-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5C_TRF_US) += board-8610-w5c-trf-us.o board-8610-w5c-trf-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W5C_SPR_US) += board-8610-w5c-spr-us.o board-8610-w5c-spr-us-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W6_GLOBAL_COM) += board-8610-w6-global-com.o board-8610-w6-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W6_GLOBAL_SCA) += board-8610-w6-global-sca.o board-8610-w6-global-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W6_TCL_MX) += board-8610-w6-tcl-mx.o board-8610-w6-tcl-mx-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W6_GLOBAL_AME) += board-8610-w6-global-ame.o board-8610-w6-global-ame-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W6DS_GLOBAL_COM) += board-8610-w6ds-global-com.o board-8610-w6ds-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W6DS_GLOBAL_SCA) += board-8610-w6ds-global-sca.o board-8610-w6ds-global-sca-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W6DS_TIM_BR) += board-8610-w6ds-tim-br.o board-8610-w6ds-tim-br-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W65_GLOBAL_COM) += board-8610-w65-global-com.o board-8610-w65-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_W65DS_GLOBAL_COM) += board-8610-w65ds-global-com.o board-8610-w65ds-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8926_JAGDSNM_CMCC_CN) += board-8926-jagdsnm.o board-8926-jagdsnm-gpiomux.o bluetooth-pm.o
obj-$(CONFIG_MACH_MSM8926_JAGDSNM_CUCC_CN) += board-8926-jagdsnm.o board-8926-jagdsnm-gpiomux.o bluetooth-pm.o
obj-$(CONFIG_MACH_MSM8926_JAGDSNM_CTC_CN) += board-8926-jagdsnm.o board-8926-jagdsnm-gpiomux.o bluetooth-pm.o

obj-$(CONFIG_MACH_MSM8X10_L70P_GLOBAL_COM) += board-8610-l70p-global-com.o board-8610-l70p-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_L70PN_GLOBAL_COM) += board-8610-l70pn-global-com.o board-8610-l70pn-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8X10_L70PDS_GLOBAL_COM) += board-8610-l70pds-global-com.o board-8610-l70pds-global-com-gpiomux.o

obj-$(CONFIG_LGE_BOOTLOADER_LOG) += lge_bootloader_log.o
obj-$(CONFIG_LGE_HANDLE_PANIC) += lge_handle_panic.o
obj-$(CONFIG_LGE_BOOTLOADER_TIME_CHECKER) += lge_bootloader_time_checker.o

ifdef CONFIG_MACH_MSM8926_X5_SPR
obj-$(CONFIG_LGE_PM_CHARGING_TEMP_SCENARIO) += lge_charging_scenario_sprint.o
else
ifdef CONFIG_MACH_MSM8X10_W5C_SPR_US
obj-$(CONFIG_LGE_PM_CHARGING_TEMP_SCENARIO) += lge_charging_scenario_sprint.o
else
ifdef CONFIG_MACH_MSM8926_JAGC_SPR
obj-$(CONFIG_LGE_PM_CHARGING_TEMP_SCENARIO) += lge_charging_scenario_sprint.o
else
obj-$(CONFIG_LGE_PM_CHARGING_TEMP_SCENARIO) += lge_charging_scenario.o
endif
endif
endif

obj-$(CONFIG_MACH_LGE) += lge_kcal_ctrl.o
obj-$(CONFIG_LGE_QSDL_SUPPORT) += lge_qsdl.o

#[WiFi]_S[sangheon.shim@lge.com] BRCM WLAN
obj-$(CONFIG_WIFI_CONTROL_FUNC) += wifi_bcm_lge.o
obj-$(CONFIG_LGE_QFPROM_INTERFACE) += lge_qfprom_access.o
obj-$(CONFIG_LGE_ENABLE_MMC_STRENGTH_CONTROL) += lge_mmc_strength_control.o

ifneq ($(CONFIG_MACH_MSM8926_X10_VZW),)
EXTRA_CFLAGS += -DCONFIG_MACH_MSM8926_X10_VZW
endif
#[Power] Battery Data
ifdef CONFIG_LGE_PM_BATTERY_PROFILE_DATA
#This is for default setting / remove later
obj-$(CONFIG_MACH_LGE) += bms-batterydata-LGE_BL_54SH_2540mAh_LG_Chem_Final.o
obj-$(CONFIG_LGE_PM_BATTERY_CAPACITY_1540mAh) += bms-batterydata-LGC_BL44JR_1540.o
ifdef CONFIG_MACH_MSM8926_VFP_KR
obj-$(CONFIG_LGE_PM_BATTERY_CAPACITY_1700mAh) += bms-batterydata-LGE_BL_44JH_1700mAh_LG_Chem_Final.o
else
obj-$(CONFIG_LGE_PM_BATTERY_CAPACITY_1700mAh) += bms-batterydata-LGC_BL44JH_1700.o bms-batterydata-LGC_BL44JH_1700_Dallas.o bms-batterydata-Tocad_BL44JH_1700_Intersil.o
endif
obj-$(CONFIG_LGE_PM_BATTERY_CAPACITY_1900mAh) += bms-batterydata-LGE_L70_CHEM_1900mAh_Final.o bms-batterydata-LGE_L70_TOCAD_1900mAh_Final.o
obj-$(CONFIG_LGE_PM_BATTERY_CAPACITY_2100mAh) += bms-batterydata-LGE_LGC_2040mAh_Final.o bms-batterydata-LGE_Tocad_2040mAh_Final.o bms-batterydata-LGE_Hitaci_2040mAh_Final.o bms-batterydata-LGE_BL41A1H_1527783_2100mAh_Final.o
obj-$(CONFIG_LGE_PM_BATTERY_CAPACITY_2440mAh) += bms-batterydata-LGE_BL_59UH_2440mAh_LG_Chem_Final.o bms-batterydata-LGE_BL_59UH_2440mAh_TOCAD_Final.o
obj-$(CONFIG_LGE_PM_BATTERY_CAPACITY_2540mAh) += bms-batterydata-LGE_BL_54SH_2540mAh_LG_Chem_Final.o bms-batterydata-LGE_BL_54SH_2540mAh_Sanyo_Final.o
obj-$(CONFIG_LGE_PM_BATTERY_CAPACITY_3000mAh) += bms-batterydata-LGE_BL_64SH_3000mAh_LG_Chem_Final.o bms-batterydata-LGE_BL_64SH_3000mAh_Technohill_Final.o
obj-$(CONFIG_LGE_PM_BATTERY_CAPACITY_3200mAh) += bms-batterydata-LGE_BL_47TH_3200mAh_LG_Chem.o bms-batterydata-LGE_BL_47TH_3200mAh_Tocad.o
obj-$(CONFIG_LGE_PM_BATTERY_CAPACITY_4000mAh) += bms-batterydata_LGE_BL_T12_4000mAh_TOCAD_Final.o bms-batterydata_LGE_BL_T12_4000mAh_LG_Chem_Final.o
obj-$(CONFIG_LGE_PM_BATTERY_CAPACITY_4200mAh) += bms-batterydata_LGE_LGC_4200.o
obj-$(CONFIG_LGE_PM_BATTERY_CAPACITY_4600mAh) += bms-batterydata_LGE_LGC_4600.o
obj-$(CONFIG_LGE_PM_BATTERY_CAPACITY_8000mAh) += bms-batterydata_LGE_BL_T13_8000mAh_TOCAD_Final.o bms-batterydata_LGE_BL_T13_8000mAh_LG_Chem_Final.o
endif

CFLAGS_devices_lge.o += -Idrivers/staging/android

obj-$(CONFIG_PRE_SELF_DIAGNOSIS) += lge_pre_selfd.o

