##########################################
# Makefile for MTV222 Device Drivers.
##########################################
ccflags-y += -Idrivers/broadcast/oneseg

obj-y += broadcast_mtv222_drv_if.o
obj-y += broadcast_mtv222.o

obj-y += raontv.o
obj-y += raontv_isdbt.o
obj-y += raontv_rf.o
obj-y += raontv_port.o

