#
# Makefile for the broadcast(ISDB-T) RF/BB core.
#
#obj-$(CONFIG_LGE_BROADCAST_ONESEG_TCC3530)		+= broadcast_dmb_drv_if.o
obj-$(CONFIG_LGE_BROADCAST_ONESEG_FC8150)		+= fc8150/
obj-$(CONFIG_LGE_BROADCAST_ONESEG_MTV222)		+= broadcast_dmb_drv_if.o
obj-$(CONFIG_LGE_BROADCAST_ONESEG_MTV222)		+= mtv222/
