ccflags-y += -Idrivers/media/platform/msm/camera_v2_8610
ccflags-y += -Idrivers/media/platform/msm/camera_v2_8610/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_8610/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
